name: simple_db
description: Simple storage wrapper around sembast
version: 0.0.3
homepage: https://github.com/wagner1343/simple-db

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path_provider: ^1.6.0
  sembast: ^2.1.3
